name: CI

on:
  push:
    branches: [ "main", "develop", "feature/**", "chore/**" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable Corepack
        run: corepack enable

      - name: Set pnpm 10.14.0
        run: corepack prepare pnpm@10.14.0 --activate

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -w run lint || echo "no lint script"

      - name: Typecheck
        run: pnpm -w run typecheck || echo "no typecheck script"

      - name: Build
        run: pnpm -w run build || echo "no build script"
